### ISSUE TITLE
When connecting with MQTTLens, program throws an error

### ISSUE THREAD

**Issue by maglite4cell** [sahajquinci/simplwmqttbroker#2]
When using the NON TLS demo on a processor, and trying to connect with MQTTLens, there is an error that gets thrown.

Steps to recreate:
1) Load NON TLS Demo to processor
2) Using MQTTLens with default settings, connect to processor
3) Look at error log.

Error:
  5. Error: splusmanagerapp.exe [App 4] # 2021-01-13 06:25:31  # Exception:Exception in customer callback function - System.InvalidOperationException: Sequence contains no elements
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source)
   at sahajquinci.MQTT_Broker.ServerBase.GetClientByIndex(UInt32 client  6. Error: splusmanagerapp.exe [App 4] # 2021-01-13 06:25:31  # Index, Boolean isWebSocketClient)
   at sahajquinci.MQTT_Broker.TCPServer.DisconnectClient(UInt32 clientIndex, Boolean withDisconnectPacket)
   at sahajquinci.MQTT_Broker.TCPServer.ConnectionCallback(TCPServer server, UInt32 clientIndex)
   at Crestron  7. Error: splusmanagerapp.exe [App 4] # 2021-01-13 06:25:31  # .SimplSharp.CrestronSockets.TCPServer.e(IAsyncResult A_0)
   at System.Net.LazyAsyncResult.InvokeCallback(Boolean asyncCompletion)
   at System.Net.Sockets.Socket.WorkerThread.doWork()
   at System.Net.Sockets.Socket.WorkerThread.doWorkI(Object o)
     8. Error: splusmanagerapp.exe [App 4] # 2021-01-13 06:25:31  # at System.Threading.ThreadPool.WorkItem.doWork(Object o)
   at System.Threading.Timer.ring()

  9. Error: splusmanagerapp.exe [App 4] # 2021-01-13 06:25:32  # Exception:Exception in customer callback function - System.InvalidOperationException: Sequence contains no elements
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source)
   at sahajquinci.MQTT_Broker.ServerBase.GetClientByIndex(UInt32 client 10. Error: splusmanagerapp.exe [App 4] # 2021-01-13 06:25:32  # Index, Boolean isWebSocketClient)
   at sahajquinci.MQTT_Broker.TCPServer.DisconnectClient(UInt32 clientIndex, Boolean withDisconnectPacket)
   at sahajquinci.MQTT_Broker.TCPServer.ConnectionCallback(TCPServer server, UInt32 clientIndex)
   at Crestron 11. Error: splusmanagerapp.exe [App 4] # 2021-01-13 06:25:32  # .SimplSharp.CrestronSockets.TCPServer.e(IAsyncResult A_0)
   at System.Net.LazyAsyncResult.InvokeCallback(Boolean asyncCompletion)
   at System.Net.Sockets.Socket.WorkerThread.doWork()
   at System.Net.Sockets.Socket.WorkerThread.doWorkI(Object o)
    12. Error: splusmanagerapp.exe [App 4] # 2021-01-13 06:25:32  # at System.Threading.ThreadPool.WorkItem.doWork(Object o)
   at System.Threading.Timer.ring()

**Comment by sahajquinci** [comment]
You experience this problem only with MQTTLens correct ?

**Comment by maglite4cell** [comment]
It seems to be only with MQTTLens.  I am able to connect without issue using MQTTBox.

**Comment by sahajquinci** [comment]
I found the bug in the code.
MQTTLens connection packet results in an error during the initial connection phase.
This results in an exception that triggers  the process of disconnecting the client .
First thing disconnect client does is retrieve the client from a list of client through an Index, but the client doesn't exist.

The reason why an exception in thrown is likely because MQTTLens doens't send an entire CONNECT packet but it arrives in pieces.

 @maglite4cell Could you check if the problem connecting with a WebSocket instead of Tcp persists ?

**Comment by maglite4cell** [comment]
I did test it with MQTTBox without an issue, but MQTTLens seems to have its own bug in it where I can not connect via ws.  When doing so, it reverts to tcp.

**Comment by sahajquinci** [comment]
As seen together MQTTLens is not MQTT 3.1.1 compliant. for this reason  I close this issue
