### ISSUE TITLE
When forcefully disconnecting a client (pull ethernet out of device) Exception is thrown

### ISSUE THREAD

**Issue by maglite4cell** [sahajquinci/simplwmqttbroker#3]
When forcefully disconnecting a client (pull ethernet out of device) Exception is thrown

Error: splusmanagerapp.exe [App 4] # 2021-01-13 18:52:19  # Exception:Exception in customer callback function - System.InvalidOperationException: Sequence contains no elements
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source)
   at sahajquinci.MQTT_Broker.ServerBase.GetClientByIndex(UInt32 client  8. Error: splusmanagerapp.exe [App 4] # 2021-01-13 18:52:19  # Index, Boolean isWebSocketClient)
   at sahajquinci.MQTT_Broker.TCPServer.DisconnectClient(UInt32 clientIndex, Boolean withDisconnectPacket)
   at sahajquinci.MQTT_Broker.TCPServer.ConnectionCallback(TCPServer server, UInt32 clientIndex)
   at Crestron  9. Error: splusmanagerapp.exe [App 4] # 2021-01-13 18:52:19  # .SimplSharp.CrestronSockets.TCPServer.e(IAsyncResult A_0)
   at System.Net.LazyAsyncResult.InvokeCallback(Boolean asyncCompletion)
   at System.Net.Sockets.Socket.WorkerThread.doWork()
   at System.Net.Sockets.Socket.WorkerThread.doWorkI(Object o)
    10. Error: splusmanagerapp.exe [App 4] # 2021-01-13 18:52:19  # at System.Threading.ThreadPool.WorkItem.doWork(Object o)
   at System.Threading.Timer.ring()

**Comment by sahajquinci** [comment]
Can you still connect other clients after a forceful disconnection ?

**Comment by maglite4cell** [comment]
No, the server crashes.

**Comment by sahajquinci** [comment]
@maglite4cell  When you forcefully disconnect a client, do you do it after a proper connection has been established ?

**Comment by maglite4cell** [comment]
Yes. I had the client running for a long while.  Then when forcefully
disconnect the error occurred.

**Comment by sahajquinci** [comment]
@maglite4cell I have a code fix, but as stated I can't test it, could I send you the fix so that you could test that it works properly ?

**Comment by maglite4cell** [comment]
Yes, did you want to create a new branch and I can test that way?

**Comment by sahajquinci** [comment]
@maglite4cell 

It's quicker to give you the code to test.

https://1drv.ms/u/s!AitXb-0tLV1Ria0uNh-bMuDYwn_VaA?e=Xi9un1

You can download here the classes to replace. This link expires tomorrow


If the code I sent you doesn't work as it is, we can create a new branch

**Comment by sahajquinci** [comment]
@maglite4cell  Please let me know if this fix solves the MQTTLens problem as well
